<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Application.Api</AssemblyName>
    <RootNamespace>Application.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application.Application\Application.Application.csproj" />
    <ProjectReference Include="..\Application.Infrastructure\Application.Infrastructure.csproj" />
  </ItemGroup>

</Project>
